builds:
  - binary: envject
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: envject
    homepage: https://github.com/michaelhenry/homebrew-envject
    tap:
      owner: michaelhenry
      name: homebrew-envject
    commit_author:
      name: michaelhenry
      email: me@iamkel.net

checksum:
  name_template: 'checksums.txt'