name: CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go test ./parser -coverprofile=coverage.out -v

      - name: Test Swift Demo sample project
        run: |
          cd Examples/swift
          go run ../../main.go --file Sources/Demo/Secrets.swift --obfuscate-for=swift
          swift test
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
