name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  attach-asset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile envject
      run: sh scripts/compile.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release.zip
        token: ${{ secrets.GH_TOKEN }}